### ISSUE TITLE
Oculus Touch S / Oculus Quest profiles redundancy?

### ISSUE THREAD

**Issue by Artyom17** [immersive-web/webxr-input-profiles#109]
**oculus-quest** **oculus-touch-s** 
These two profiles are identical and this is because it is the same controllers pair, just used with different headset. Everything is going to be identical for them - mappings, renderings, fallbacks, etc. Why do we need both, I think we can actually leave only one of them - **oculus-touch-s**.

**Comment by NellWaliczek** [comment]
Happy to get rid of one.  Are you sure you want to get rid of the **oculus-quest** and not the other one?

**Comment by Artyom17** [comment]
Yes, since the controllers are still called Oculus Touch (S) and Quest is just a headset that is used with these controllers.

**Comment by Artyom17** [comment]
We had a discussion in Oculus and it seems like the consensus is to call those 'oculus-touch-v1' (the Rift), 'oculus-touch-v2' (Quest/RiftS), 'oculus-touch-v3' (next gen). It doesn't make sense to tie up the controllers to a headset, since it is possible that different headsets will work with different generations of the Oculus Touch controllers.
As to the issue with the thumbrest which is present in 'oculus-touch-v1' and not in '-v2': if it is easier then let just not expose thumbrest for the oculus-touch-v1.

**Comment by NellWaliczek** [comment]
When fixed, let's make sure the polyfill is also updated!

**Comment by toji** [comment]
Working on this update now for both this update and the polyfill. One question: I assume that most controllers will not start life with a "v1" identifier, and the only reason it seems appropriate here is because we're already aware of a second variant of the controller. (We wouldn't call the Oculus Go controller `oculus-go-v1`, for example.) As such calling the first iteration `oculus-touch` and the S/Quest variant `oculus-touch-v2` seems like it will fit the general pattern better long term?

I'm fine with whatever Oculus wants to do, just pointing out that it may leave the first-gen touch as a bit of an outlier.

**Comment by Artyom17** [comment]
@toji That is a good point about "v1". I agree, let call "oculus-touch", "oculus-touch-v2", "oculus-touch-v3", etc. 
Also, what have we decided about the exposing thumbrest for "oculus-touch" (that doesn't exist on v2, but may again exist on v3)?

**Comment by toji** [comment]
Thanks Artem! Put up a pull request for that change just now and will update the polyfill to match ASAP.

Regarding the thumb rest, I'm happy to take whatever direction Oculus wants on that, but again I think we should consider that the touch is an outlier given that we're forming these rules when there are already two variants out. I gave a more detailed answer in #79, but the short version is we have to assume that in similar cases where the previous device has already been exposed to WebXR for a while we'd probably encourage the manufacturer to either not claim it's a valid fallback or introduce a dummy button/axis for compatibility.
