### ISSUE TITLE
Add behavior for unknown gamepads

### ISSUE THREAD

**Issue by NellWaliczek** [immersive-web/webxr-input-profiles#14]
"unknown" gamepad ids may appear if the hardware is unidentifyable by the user agent or if the user agent has provided users a way to mask their gamepad id for privacy reasons.  In this situation, a mapping and asset should be present to fall back to.  This same fallback should be used if the gamepad id does not have a mapping in the repo.

**Comment by NellWaliczek** [comment]
This probably should be the `button-controller` profile, but I'm hesitant to make that change until we've addressed https://github.com/immersive-web/webxr/issues/774

**Comment by NellWaliczek** [comment]
When this issue was originally filed, we were still figuring out the details of the `profiles` attribute.  Now that we've gotten further along, a few other things should be considered:
1.  In some cases the UA will be unable to identify a vendor-prefixed string.  Should `profiles = []` in that case?  What if a `generic` prefixed string can be identified?
1. In some cases the UA will allow users to hide the actual vendor-prefixed information.  Should `profiles=[]` or should a generic be reported? If so, is it up to the UA to decide how specific that generic is (i.e. if `generic-trigger-grip` is valid, should `generic-trigger` ever be returned?)
1. If we decide to add `squeeze` events, does the `profiles` array need to indicate that this event can be fired?
1. If we allow `profiles` to be an empty array, do we have any concerns about developers falling into a pit of failure?
1. Is there any situation in which `""` would be a valid profile id?

This is related to #105 and https://github.com/immersive-web/webxr-gamepads-module/issues/23 

/agenda

**Comment by toji** [comment]
My thoughts on the questions Nell asked:

 1. I do feel like an empty array is appropriate when we have no additional useful information to provide, either due to lack of information or intentional masking. Identifying a special string to represent this state seems like unnecessary work.
 2. I do feel like it's appropriate for the UA to decide how much information they are comfortable exposing, and we shouldn't force even generics to be exposed if the UA would prefer not to. That being said, I think pretty much all UAs will find it better for content compatibility to expose at least a relevant generic type, so it's likely a self moderating issue. I would also say it should be left up to the UA how specific they want to be in what generics are exposed, as long as those generics accurately represent the data being exposed. IE: It's probably fine to return `generic-trigger` if it could actually be considered a `generic-trigger-thumbstick`, but in that case the gamepad arrays returned probably shouldn't expose the thumbstick axis/button info (which seems like it would leak the info the UA is trying to mask anyway.)
 3. I'm concerned about profiles becoming a dumping ground for input metadata, so I'm not sure that a "squeezable" profile marker is necessary. That said, many of the generic types indicate the presence of a squeeze component and I imagine that said component will pretty much always trigger the squeeze event. If we do hear consistent feedback from developers that the lack of a clear indication of squeezability is a problem, I imagine that a `squeezable` boolean on the `XRInputSource` would be an appropriate (and additive) signal.
 4. The likely failure pit for an empty array is the same as someone scanning through the an actual array and not finding any matching profiles in their controller mesh cache. In an ideal world that latter case should be exceedingly rare, but in reality if we even introduce a new generic type it's likely to start hitting this "not found" case. Best practice for apps/libraries will always be to consider a scenario where no matches are found (maybe with a "unidentified tracked blob" mesh?) and if they don't follow it then the presence of a special unknown string still won't be enough to save them from every potential failure case.
 5. I don't see any situations where an empty string profile would be useful or communicate something other than the same state suggested by an empty array.

**Comment by Manishearth** [comment]
I don't have strong opinions on this but I tend to agree with @toji's comment here. A `squeezable` bool is also an interesting idea.

So I'd weakly advocate for allowing empty arrays (but non-empty arrays must end in a generic).

**Comment by NellWaliczek** [comment]
Sounds like consensus on this was that unknown XRInputSources would simply report an empty profiles array.  In that case, what is the expectation of the motion-controller library?  Should it be showing anything at all?  If it doesn't display anything handheld, I imagine we'll see a bunch of floating targeting rays...?  maybe that's ok?

**Comment by toji** [comment]
I would expect that it's something the app would decide based on content. If the app is ray-interaction-based a floating ray pointer is probably enough to use the app, even if it's not pretty. If the app is based around more direct interactions they would probably know that they need a fallback visual and have some sort of default controller model available.

**Comment by NellWaliczek** [comment]
Ah I should have perhaps been clearer... what do we want to have the library built out of the motion-controllers package do? The Profiles.fetchProfile() takes an XRInputSource and just grabs the correct JSON/asset URLs.  Should it return generic-button if the array is []?  Should that be an optional parameter?

**Comment by toji** [comment]
Ah, I see what the issue is. I thought that the `fetchProfile()` took an array of profiles, not the `XRInputSource`. If it did then the developer could just append the desired fallback profile to the end of the list.

Given that's not the function signature, though (and I don't think we should change it, handling the handedness automatically is nice) I think an optional parameter for a "default profile" is probably not a terrible idea. Set it to `generic-button` or `generic-trigger` (which is probably the more common subset?) by default and let developers override it to `null`/empty string if they want to allow the failure to surface.
