### ISSUE TITLE
Add missing profiles and assets

### ISSUE THREAD

**Issue by NellWaliczek** [immersive-web/webxr-input-profiles#40]
There are a number of profiles missing for known valid hardware.  In addition, the profiles that exist are missing assets to go with them.  This issue tracks getting assets added, node names updated in existing profiles, and missing profiles added as well.

**Comment by NellWaliczek** [comment]
Generic assets added in #126 and #127

**Comment by toji** [comment]
Been hunting down, rigging, and adding assets for all of the remaining profiles. Once #146 and #147 land we'll have profiles and assets for pretty much all of the major consumer devices, with the exception of Magic Leap (which should not have a controller visualization anyway) and the `generic-touchscreen` profile (for obvious reasons).

As such, I'm considering this closed. Obviously there's a huge long tail of devices that could be added, but I would really prefer that we get to a state where the manufacturers themselves are the ones registering them and providing the models. It'll quickly become unmanagable for the Immersive Web group to keep up otherwise.
