### ISSUE TITLE
Do fallback profiles need to contain only subset of componenents?

### ISSUE THREAD

**Issue by NellWaliczek** [immersive-web/webxr-input-profiles#79]
Per the comment here: https://github.com/immersive-web/webxr-input-profiles/issues/71#issuecomment-524106055

Should Oculus Quest not be allowed to have Oculus Touch as a fallback profile because there is an extra thumbrest button on the latter?

**Comment by NellWaliczek** [comment]
Filed #100 to specifically address the Oculus Touch profile.

/agenda To hear opinions on what the general guidelines ought to be

**Comment by Artyom17** [comment]
I am trying to understand how this fallback mechanism supposed to work... It is an UA which actually fills profile names on XRInputSource, so it knows everything about supported controllers. Then user's code fetches profiles (fetchProfile func) and uses the profile id to match the actual json profile. In which case it may not find the proper matching? When the UA requests some new hardware and there is no profile for it yet in that profile json? Who is responsible for updating that profile json and why this gonna be a case at all, if that profile json is updated in timely manner?

Anyhow, it is perfectly normal that next version of the hardware has some features removed and then potentially re-added and even newer iteration. I am not sure what is more logical to do here:
1) Allow fallback to older but more featurefull HW: what would those extra features report in the case of fallback?
2) Add a dummy feature (thumbrest) to Oculus Touch-S/Quest, which will be presented but never actually do anything; in fact, this is how WebVR gamepad implementation is currently done in Oculus Browser.
3) Do not expose thumbrest at all, even for Oculus Touch: don't like this idea, while it can provide a quick fix for now, I bet in the future we may see other cases like Oculus Touch S / Oculus Touch.

I am leaning to solution # 1 and we just need to make sure that the extra features are reported but you can't get status change on them (like thumbrest will never report any values, if Oculus Touch profile is used with Oculus Touch S / Quest).

**Comment by toji** [comment]
To answer some of @Artyom17's questions: Ideally new profiles would be added to the registry by the company that creates the hardware, but that will require a certain amount of momentum before they'll spontaneously do it. As a result it's likely to be community driven to start and that'll undoubtedly result in periods where hardware is reporting a profile with no associated registry entry/json/model. That's when the fallback will be most applicable. (Also, it's not unreasonable for some web apps to want to use their own cache of the json/models which will probably be out of date to some degree.)

As for the fallback behavior, I think the options Artem outlines are all reasonable to some degree, though I have a few thoughts to add:

First, I don't think the presence or absence of the thumbrest is nearly as impactful as if it was a proper button that had been dropped in a later hardware revision. But there is a small chance that a developer could recognize the `oculus-touch` profile and, based on the accompanying JSON description of the profile, blindly try to access `buttons[7]` and get an index out of bounds error. That's something that can be largely avoided by ensuring that our libraries and other popular integrations are doing some common sense checks, but at the end of the day it's still suggests that it would be better to either omit it from both or include a placeholder element in the later profile.

With that in mind, it's worth noting that most of these fallback scenarios are going to evolve over a much longer time period than the touch/quest situation, where we're defining their layouts simultaneously. We should assume that it will be more common for a device like touch to be released and then followed up on N years later with a device that wants to use it as a fallback. In the touch case the thumb rest would have already been accessible for a few years prior to the quest controllers coming out, and normally removing that output wouldn't be considered, so that effectively would force the quest controller to expose a placeholder element in order to use the original touch as a fallback. (No surprise that this is exactly the route Artem says Oculus went anyway with the WebVR implementation, despite not having profiles.)

In my opinion we probably shouldn't be listing more featureful devices as fallbacks in the first place, but we've already seen scenarios where it makes sense and I expect that to continue over time. I think we should at least highly discourage it if the missing capabilities are material (ie: used more directly than the thumbrest), and in the cases that it is done the gamepad value arrays should expose at least placeholder elements for the missing values.

**Comment by Artyom17** [comment]
I am more than happy to have a dummy thumbrest for oculus-touch-v2; in fact, this is how it was in WebVR for compatibility with Rift's Touch (v1). Seem most logical and I agree with @toji that usually the v1 device is released much earlier and we can't remove features from it.

**Comment by Artyom17** [comment]
Trying to make a dummy thumbrest for oculus-touch-v2, but having issues (https://github.com/immersive-web/webxr-input-profiles/issues/115)

**Comment by toji** [comment]
This issue seems pretty well resolved at this point. Using a fallback profile for a device that has more components than the one you're adding is discouraged, but in the cases where it's warranted (Such as the above example of Oculus Touch -> Oculus Touch V2, which lacks a thumbrest) a placeholder component should be put in place to prevent application errors.

Closing.
