### ISSUE TITLE
Figure out and document stability of fallback chains

### ISSUE THREAD

**Issue by Manishearth** [immersive-web/webxr-input-profiles#99]
See also https://github.com/immersive-web/webxr-input-profiles/issues/98

I and @toji discussed this a bit yesterday, and we're interested in hearing what others think. It seems to us like we should have no stability constraints on fallback chains: we're free to update them however we wish, provided there is always a generic fallback. Perhaps it could be a bit more nuanced (e.g. "the generic fallback will never change"), but it feels like there should be a policy here, and we should document it.

If we do this, issues like #98 become less pressing.

The reasoning behind not having stability requirements is that if you're _relying_ on a certain fallback chain you can just as easily code for the specific device, the fallback chain basically only exists for unknown devices to be compatible with code written for similar devices.

**Comment by thetuvix** [comment]
Some changes would be more breaking that others - if we included `"htc-vive"` as a fallback for `"valve-index"` here, for example, and then later removed it, that would break any sites that had supported Valve Index controllers solely through their support for the HTC Vive profile.

Maybe then, we'd err on the side of less fallbacks at first, since we're comfortable adding them?

**Comment by Manishearth** [comment]
@thetuvix Right, what I'm trying to say is that if a site _wanted_ to support valve index controllers in a stable fashion, they should request that profile. Otherwise we provide no stability guarantee.

As a design principle from our side it makes sense to be cautious: we can both have no strict stability guarantee and _still_ try to maintain some level of stability :smile:

**Comment by toji** [comment]
Agreed with @Manishearth that we want to encourage stability but allow device manufacturers and UAs to do what they feel is best for their user base.

There's a lot of interesting edge-case scenarios that may lead to a desire to play with the fallback list, and being overly prescriptive here. Consider:

- It's easy to see scenarios like the Quest quickly overtaking the Rift in terms of popularity among developers. Wouldn't be surprised if at some point Oculus could see it as beneficial to list the Quest controller as the fallback for the Rift controller rather than visa-versa, because it nets them more functional experiences that way.
- If a device is recalled because, say, the controllers explode in the users hands (that newfangled haptics system just didn't work out...) it's absolutely plausible that a manufacturer that previously was happy to list that device as a fallback now no longer wants their controller associated with controller-mc-explody-face.
- Browsers that support multiple devices will have to store multiple fallback lists internally, which eats up space no matter how minor. It's reasonable to expect them to want to do a cleanup pass every once in a while and say: "Hey, stats show that this N-year-old fallback is ~never used. We're gonna scrub it."

**Comment by Manishearth** [comment]
We discussed this a bit today, we seem to be agreement in:

 - Entry 0 will be the device specific identifier that never changes (if we want it to change, it's a new profile)
 - The last entry must be a generic, but it may change (we may add better generics)
 - All other entries have no stability guarantees and can be changed

**Comment by NellWaliczek** [comment]
Readme.md should be updated to state this explicitly.
